os: osx
language: c
sudo: enabled
env: OMP_NUM_THREADS=1
addons:
  homebrew:
    packages:
    - gfortran
before_install: true
install:
  - mkdir build
  - cd build
  - cmake ../
  - make
script:
  - make test
