language: c
sudo: enabled
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran liblapack-dev cmake
  - pip install numpy --user
install:
  - mkdir build
  - cd build
  - cmake ../
  - make
script:
  - make test