language: c
sudo: enabled
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran liblapack-dev cmake
install:
  - mkdir build
  - cd build
  - cmake ../
  - make
script:
  - cd build
  - make test