matrix:
  include:
  - language: c
    sudo: enabled
    env: OMP_NUM_THREADS=1
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gfortran liblapack-dev cmake
      - pip install numpy --user
    install:
      - mkdir build
      - cd build
    script:
      - cmake ../
      - make
      - export OMP_NUM_THREADS=1
      - make test
      - rm -r test
      - make
      - export OMP_NUM_THREADS=3
      - make test
      - rm -r *
      - sudo apt-get install -y libopenmpi-dev openmpi-bin
      - cmake ../
      - make
      - export OMP_NUM_THREADS=1
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
      - export OMP_NUM_THREADS=3
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
      - export OMP_NUM_THREADS=1
      - make test MPIRUN="mpiexec -np 16"
      - rm -r test
      - make
      - export OMP_NUM_THREADS=3
      - make test MPIRUN="mpiexec -np 16"
